[0.026s] Invoking command in '/home/clem/ros2_ws/build/interface_acquisition': CMAKE_PREFIX_PATH=/opt/ros/humble /usr/bin/cmake /home/clem/ros2_ws/src/interface_acquisition -DCMAKE_INSTALL_PREFIX=/home/clem/ros2_ws/install/interface_acquisition
[0.034s] -- Found ament_cmake: 1.3.5 (/opt/ros/humble/share/ament_cmake/cmake)
[0.121s] -- Found ament_lint_auto: 0.12.8 (/opt/ros/humble/share/ament_lint_auto/cmake)
[0.161s] -- Found rosidl_default_generators: 1.2.0 (/opt/ros/humble/share/rosidl_default_generators/cmake)
[0.162s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.163s] -- Found rosidl_adapter: 3.1.5 (/opt/ros/humble/share/rosidl_adapter/cmake)
[0.180s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.297s] [31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
[0.297s]   execute_process(/usr/bin/python3.10 -m rosidl_adapter --package-name
[0.297s]   interface_acquisition --arguments-file
[0.297s]   /home/clem/ros2_ws/build/interface_acquisition/rosidl_adapter__arguments__interface_acquisition.json
[0.297s]   --output-dir
[0.297s]   /home/clem/ros2_ws/build/interface_acquisition/rosidl_adapter/interface_acquisition
[0.297s]   --output-file
[0.297s]   /home/clem/ros2_ws/build/interface_acquisition/rosidl_adapter/interface_acquisition.idls)
[0.297s]   returned error code 1:
[0.297s] 
[0.297s]   Traceback (most recent call last):
[0.297s] 
[0.297s]     File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[0.297s]       return _run_code(code, main_globals, None,
[0.297s]     File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[0.297s]       exec(code, run_globals)
[0.297s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
[0.297s]       sys.exit(main())
[0.297s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
[0.297s]       abs_idl_file = convert_to_idl(
[0.297s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 24, in convert_to_idl
[0.297s]       return convert_srv_to_idl(
[0.297s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/srv/__init__.py", line 28, in convert_srv_to_idl
[0.297s]       srv = parse_service_string(package_name, input_file.stem, content)
[0.297s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 859, in parse_service_string
[0.298s]       request_message = parse_message_string(
[0.298s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 544, in parse_message_string
[0.298s]       msg = MessageSpecification(pkg_name, msg_name, fields, constants)
[0.298s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 388, in __init__
[0.298s]       self.base_type = BaseType(
[0.298s]     File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 205, in __init__
[0.298s]       raise InvalidResourceName(
[0.298s] 
[0.298s]   rosidl_adapter.parser.InvalidResourceName: 'Creation_fichier_ply_Request'
[0.298s]   is an invalid message name.  It should have the pattern
[0.298s]   '^[A-Z][A-Za-z0-9]*$'
[0.298s] 
[0.298s] Call Stack (most recent call first):
[0.298s]   /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[0.298s]   CMakeLists.txt:28 (rosidl_generate_interfaces)
[0.298s] 
[0.298s] [0m
[0.298s] -- Configuring incomplete, errors occurred!
[0.298s] See also "/home/clem/ros2_ws/build/interface_acquisition/CMakeFiles/CMakeOutput.log".
[0.301s] Invoked command in '/home/clem/ros2_ws/build/interface_acquisition' returned '1': CMAKE_PREFIX_PATH=/opt/ros/humble /usr/bin/cmake /home/clem/ros2_ws/src/interface_acquisition -DCMAKE_INSTALL_PREFIX=/home/clem/ros2_ws/install/interface_acquisition
